name: 'Corne-ish Zen V2'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    with:
      board: '["corneish_zen_v2_left","corneish_zen_v2_right"]'
      custom_config: '["#define MIRYOKU_KLUDGE_MOUSEKEYSPR\n#define MIRYOKU_TAP=QWERTY\n #define MIRYOKU_EXTRA=COLEMAKDH"]'
      kconfig: '["CONFIG_ZMK_MOUSE=y\nCONFIG_ZMK_DISPLAY_HIDE_MOMENTARY_LAYERS=y\nCONFIG_IL0323_INVERT=n\nCONFIG_CUSTOM_WIDGET_LAYER_STATUS_HIDE_HEADING=y\nCONFIG_CUSTOM_WIDGET_LOGO_IMAGE_MIRYOKU=y"]'
      branches: '["zmkfirmware/zmk/main caksoylar/zmk/caksoylar/zen-v1+v2 petejohanson/zmk/feat/pointers-move-scroll"]'
      alphas: '["QWERTY"]'
      nav: '["vi"]'
