name: 'Corne-ish Zen V2'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    with:
      board: '["corneish_zen_v2_left","corneish_zen_v2_right"]'
      kconfig: '["CONFIG_ZMK_DISPLAY_HIDE_MOMENTARY_LAYERS=y\nCONFIG_IL0323_INVERT=n\nCONFIG_CUSTOM_WIDGET_LAYER_STATUS_HIDE_HEADING=y\CONFIG_CUSTOM_WIDGET_LOGO_IMAGE_MIRYOKU=y"]'
      branches: '["zmkfirmware/zmk/main caksoylar/zmk/caksoylar/zen-v1+v2"]'
      alphas: '["QWERTY"]'
      nav: '["vi"]'
